name: Uptime

on:
  schedule:
    - cron: "5 * * * *"

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Check Sites
    steps:
      - uses: actions/checkout@v2
      - name: Run Shell Script
        id: shell_script_run
        run: bash ./check.sh "${{ secrets.user }}" "${{ secrets.email }}"
